spring:
  application:
    name: JobOpportunity
  profiles:
    active: dev
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: ./../message/mesage
  output:
    ansi:
      console-available: true

JobOpportunity:
  clientApp:
    name: 'JobOpportunity'
  mail:
    from: JobOpportunity@localhost

app:
  security:
    secret: ZjEwZGM5YWY0MzQxNTMzZDMwMWYwYmQzNmRjMDNlN2EyOWI2MWRjZWVmMDBhY2EwN2Q1YTZjY2E5YjNiMDE5YTZhNWM4ZjUzNGEwMjgxYThiNGE1Y2ZiYzE4YzU0NGY4MjBkZmVmMzgzZmVkYmUwMGVlZWFhYzkwZjNlM2Q5M2Q=
    expiration: 7464960000
  email:
    from: huynhnqt01@gmail.com
    password: qihmraycgbyfnsyr